# Machine specific configuration
MachineConfigs:

  devosi-tests: # Name of machine (given by the "hostname" command)
    ice_charts: /data2/ice_charts/gridded/ # base ice-chart directory
    results: /data2/validations/ # results directory
    mongodb_ip: None # TODO: Enter database info

  pallas: # Name of machine (given by the "hostname" command)
    ice_charts: /data/jol/ice_charts/gridded/ # base ice-chart directory
    results: /data/jol/results/ # results directory
    mongodb_ip: None # TODO: Enter database info

    # Add your new machine config here


# Sets of validation arguments
Validations:

  # Template set validation arguments
  Example: # Name of validation set
    url: http//example.com/path/to/netcdf.nc # http or ftp address to OSI SAF data to validate
    icechart_dir: relative_path # The relative path to the ice charts directory.
                                      # The base path is given above in MachineConfigs
    validator: ValidationClass # The validation class in validate_conc.py or validate_edge.py.
                               # Use and existing class or make a subclass.


  # Sea Ice Conc: SSMIS

  ice_conc_ssmis_http:
    url: http://thredds.met.no/thredds/dodsC/osisaf/met.no/ice/conc/{Y}/{m:02d}/ice_conc_{hem}_polstere-100_multi_{Y}{m:02d}{d:02d}1200.nc
    icechart_dir: OSISAF
    validator: ValidateConcHYR

  ice_conc_ssmis_ftp:
    url: ftp://osisaf.met.no/archive/ice/conc/{Y}/{m:02d}/ice_conc_{hem}_polstere-100_multi_{Y}{m:02d}{d:02d}1200.nc
    icechart_dir: OSISAF
    validator: ValidateConcHYR


  # Sea Ice Conc: AMSR-2 OSHD

  ice_conc_amsr_oshd_http:
    url: http://thredds.met.no/thredds/dodsC/osisaf/met.no/ice/amsr2_conc/{Y}/{m:02d}/ice_conc_{hem}_polstere-100_amsr2_{Y}{m:02d}{d:02d}1200.nc
    icechart_dir: OSISAF
    validator: ValidateConcHYR

  ice_conc_amsr_oshd_ftp:
    url: ftp://osisaf.met.no/archive/ice/conc_amsr/{Y}/{m:02d}/ice_conc_{hem}_polstere-100_amsr2_{Y}{m:02d}{d:02d}1200.nc
    icechart_dir: OSISAF
    validator: ValidateConcHYR


  # Sea Ice Conc: AMSR-2 TUD

  ice_conc_amsr_tud_ftp:
    url: ftp://osisaf.met.no/archive/ice/conc_amsr/{Y}/{m:02d}/ice_conc_{hem}_polstere-100_amsr2-tud_{Y}{m:02d}{d:02d}1200.nc
    icechart_dir: OSISAF
    validator: ValidateConcHYR

  ice_conc_amsr_tud_http:
    url: http://thredds.met.no/thredds/dodsC/osisaf/met.no/ice/amsr2_conc/{Y}/{m:02d}/ice_conc_{hem}_polstere-100_amsr2-tud_{Y}{m:02d}{d:02d}1200.nc
    icechart_dir: OSISAF
    validator: ValidateConcHYR


  # Sea Ice Edge

  ice_conc_edge_ftp:
    url: ftp://osisaf.met.no/archive/ice/edge/{Y}/{m:02d}/ice_edge_{hem}_polstere-100_multi_{Y}{m:02d}{d:02d}1200.nc
    icechart_dir: OSISAF
    validator: ValidateEdge

  ice_conc_edge_http:
    url: http://thredds.met.no/thredds/dodsC/osisaf/met.no/ice/edge/{Y}/{m:02d}/ice_edge_{hem}_polstere-100_multi_{Y}{m:02d}{d:02d}1200.nc
    icechart_dir: OSISAF
    validator: ValidateEdge

  # (I)CDF

  ice_conc_icdr_osi430_http:
    url: http://thredds.met.no/thredds/dodsC/osisaf/met.no/reprocessed/ice/conc_cr_files/{Y}/{m:02d}/ice_conc_{hem}_polstere-100_cont-reproc_{Y}{m:02d}{d:02d}1200.nc
    icechart_dir: OSISAF
    validator: ValidateConcCDR

  ice_conc_icdr_osi430b_http:
    url: http://thredds.met.no/thredds/dodsC/metusers/thomasl/OSI430B_draft/250/{Y}/{m:02d}/ice_conc_{hem}_ease2-250_icdr-v2p0_{Y}{m:02d}{d:02d}1200.nc
    icechart_dir: EASE2
    validator: ValidateConcCDR



  # Add new validation config here...


# Add the validation name to a list here:
ValidationsToRun:

  # These are lists of validations run at DMI

  # These use OpenDAP
  ProductionDMI:
    - ice_conc_ssmis_http
    - ice_conc_amsr_oshd_http
    - ice_conc_amsr_tud_http
    - ice_conc_edge_http

  # The FTP servers have the full time series
  ArchivedDMI:
    - ice_conc_ssmis_ftp
    - ice_conc_amsr_oshd_ftp
    - ice_conc_amsr_tud_ftp
    - ice_conc_edge_ftp

  ICDR:
    - ice_conc_icdr_osi430_http
    - ice_conc_icdr_osi430b_http

  # Add a new list here:
